gpio:
  pin: 16
  pull_up: false
  bounce_time_seconds: 0.1
  high_confirm_seconds: 2
  low_confirm_seconds: 5

paths:
  save_dir: "~/coil_images"
  camera_temperature_log_file: "~/coil_images/camera_temp.log"

upload:
  url: "http://192.168.0.106:5000/upload"
  timeout_seconds: 120
  retry_delay_seconds: 2

camera_runtime:
  reconnect_interval_seconds: 5
  temperature_log_interval_seconds: 10
  profile_check_interval_seconds: 5

logging:
  level: "INFO"
  console: true
  file: "~/coil_images/capture.log"
  remove_spam_logs: true

cameras:
  - name: "CAM1"
    device_index: 0
    serial_number: null
    exposure_time: 500000.0
    gain_value: 10.0
    profiles:
      - name: "day"
        exposure_time: 500000.0
        gain_value: 10.0
        start: "06:00"
      - name: "night"
        exposure_time: 500000.0
        gain_value: 10.0
        start: "18:00"
    captures:
      - name: "CAP1"
        delay_after_previous_seconds: 10
      - name: "CAP2"
        delay_after_previous_seconds: 6
  - name: "CAM2"
    device_index: 1
    serial_number: null
    exposure_time: 500000.0
    gain_value: 10.0
    profiles:
      - name: "day"
        exposure_time: 500000.0
        gain_value: 10.0
        start: "06:00"
      - name: "night"
        exposure_time: 500000.0
        gain_value: 10.0
        start: "18:00"
    captures:
      - name: "CAP1"
        delay_after_previous_seconds: 10
      - name: "CAP2"
        delay_after_previous_seconds: 6
